# Generated by Django 5.2.10 on 2026-02-06 07:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_is_accepted_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
