[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --nomigrations --cov=apps --cov-report=term-missing
testpaths = apps tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
