# Generated by Django 5.2.10 on 2026-02-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Escrow', 'verbose_name_plural': 'Escrows'},
        ),
    ]
