# Generated by Django 5.2.10 on 2026-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
