# Generated by Django 5.2.10 on 2026-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
