# Generated by Django 5.2.12 on 2026-03-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_category_name_ru_category_name_tk'),
        ('profiles', '0009_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='jobs.category', verbose_name='Primary Category'),
        ),
    ]
