# Generated by Django 5.2.12 on 2026-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_tk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ady (TK)'),
        ),
    ]
