# Generated by Django 5.2.12 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_add_translation_fields_to_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_velayat',
            field=models.CharField(blank=True, choices=[('ASHGABAT', 'Ashgabat'), ('AHAL', 'Ahal'), ('BALKAN', 'Balkan'), ('DASHOGUZ', 'Dashoguz'), ('LEBAP', 'Lebap'), ('MARY', 'Mary')], max_length=20, null=True, verbose_name='Region/Velayat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='City/District/Address'),
        ),
    ]
