# Generated by Django 5.2.10 on 2026-02-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BLOCK_USER', 'Block User'), ('UNBLOCK_USER', 'Unblock User'), ('ADJUST_BALANCE', 'Adjust Balance'), ('FORCE_ESCROW_RELEASE', 'Force Escrow Release'), ('FORCE_ESCROW_REFUND', 'Force Escrow Refund'), ('VERIFY_USER', 'Verify User'), ('VIP_USER', 'VIP User'), ('BROADCAST', 'System Broadcast')], max_length=50)),
                ('target_info', models.CharField(help_text='e.g. User ID: 5, Job ID: 10', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Reason for the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
