# Generated by Django 5.2.10 on 2026-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(choices=[('BLOCK_USER', 'Block User'), ('UNBLOCK_USER', 'Unblock User'), ('ADJUST_BALANCE', 'Adjust Balance'), ('FORCE_ESCROW_RELEASE', 'Force Escrow Release'), ('FORCE_ESCROW_REFUND', 'Force Escrow Refund'), ('VERIFY_USER', 'Verify User'), ('VIP_USER', 'VIP User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('BROADCAST', 'System Broadcast')], max_length=50),
        ),
    ]
