# Generated by Django 5.2.12 on 2026-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_adminlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_delete_enabled', models.BooleanField(default=True, help_text='If enabled, soft-deleted accounts will be automatically permanently anonymized.')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to keep a soft-deleted account before anonymizing.')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
