# Generated by Django 5.2.12 on 2026-03-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='delete_avatar',
            field=models.BooleanField(default=True, help_text='Delete profile avatar from storage'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_bio',
            field=models.BooleanField(default=True, help_text='Erase profile biography, profession, location, and phone number'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_email',
            field=models.BooleanField(default=False, help_text='Completely obfuscate email address (e.g., deleted_1_user@domain becomes deleted_1@archived.local)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_messages',
            field=models.BooleanField(default=True, help_text='Delete all chat messages sent by the user (including attachments)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_name',
            field=models.BooleanField(default=True, help_text='Erase first and last name'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_portfolio',
            field=models.BooleanField(default=True, help_text='Delete all portfolio items and their media'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_skills',
            field=models.BooleanField(default=True, help_text='Remove skills, languages, and experience years'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='delete_social_links',
            field=models.BooleanField(default=True, help_text='Remove linked social network profiles'),
        ),
    ]
