# Generated by Django 5.2.12 on 2026-04-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_systemsetting_delete_avatar_systemsetting_delete_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive to add, negative to subtract', max_digits=12, verbose_name='Amount')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_comment', models.TextField(blank=True, help_text='Reason for approval or rejection', verbose_name='Admin Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_balance_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_balance_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustment_targets', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'Balance Adjustment Request',
                'verbose_name_plural': 'Balance Adjustment Requests',
                'db_table': 'balance_adjustment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
