# Generated by Django 5.2.12 on 2026-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auto_approve_withdrawals',
            field=models.BooleanField(default=False, help_text='If enabled, withdrawal requests are automatically approved and funds act as immediately withdrawn.'),
        ),
    ]
