# Generated by Django 5.2.10 on 2026-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_remove_user_roles_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='User is blocked until this time', null=True),
        ),
    ]
