# Generated by Django 5.2.10 on 2026-02-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminrole'),
        ('users', '0004_passwordresetcode'),
    ]

    operations = [
    ]
