# Generated by Django 5.2.10 on 2026-02-15 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0002_adminrole_0004_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_role',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
