# Generated by Django 5.2.12 on 2026-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
