# Generated by Django 5.2.10 on 2026-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ESCROW_LOCK', 'Escrow Lock'), ('ESCROW_RELEASE', 'Escrow Release'), ('ESCROW_REFUND', 'Escrow Refund'), ('FEE', 'Fee'), ('PURCHASE_VIP', 'Purchase VIP')], max_length=20),
        ),
    ]
