# Generated by Django 5.2.10 on 2026-02-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Description or links to the work results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, related_name='submissions', to='jobs.jobfile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Submission',
                'verbose_name_plural': 'Job Submissions',
                'db_table': 'job_submissions',
            },
        ),
    ]
