# Generated by Django 5.2.10 on 2026-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
    ]
