# Generated by Django 5.2.10 on 2026-02-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('DISPUTE', 'Dispute'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('DISPUTE', 'Dispute'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Status Log',
                'verbose_name_plural': 'Job Status Logs',
                'db_table': 'job_status_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
