# Generated by Django 5.2.12 on 2026-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (TK)'),
        ),
    ]
