# Generated by Django 5.2.10 on 2026-02-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('JOB', 'Job'), ('PERSONAL', 'Personal'), ('SYSTEM', 'System')], default='PERSONAL', max_length=20),
        ),
    ]
