# Generated by Django 5.2.10 on 2026-02-15 17:12

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment_thread_hidden_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.chat.models.get_chat_attachment_path),
        ),
    ]
