# Generated by Django 5.2.10 on 2026-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipplan',
            options={'ordering': ['months', 'price_per_month'], 'verbose_name': 'VIP Plan', 'verbose_name_plural': 'VIP Plans'},
        ),
        migrations.AlterField(
            model_name='vipplan',
            name='badge_icon',
            field=models.CharField(choices=[('Award', 'Award'), ('Zap', 'Zap'), ('ShieldCheck', 'ShieldCheck'), ('Star', 'Star'), ('Crown', 'Crown')], default='Award', help_text='Lucide icon name', max_length=50),
        ),
    ]
