# Generated by Django 5.2.12 on 2026-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_alter_vipplan_options_alter_vipplan_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue accumulated by the platform (VIP, commissions, etc.)', max_digits=15),
        ),
    ]
